version: "3.8"
services:
  proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false

      - DB_USER=username
      - DB_PASS=password
      - DB_NAME=local-ddi
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
  db_cli:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@user.com
      - PGADMIN_DEFAULT_PASSWORD=password
volumes:
  reserved:
