name: Push to GCR GitHub Action
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  # From https://raw.githubusercontent.com/RafikFarhad/push-to-gcr-github-action/master/.github/workflows/build_and_push.yaml
  #   (example with gcloud service account key)
  #   I preferred using "google-github-actions/auth@v0" for auth bc later steps (e.g. k8s deploy) will also require auth -Dean
  build-and-push-to-gcr-service-account:
    name: Build & push - with service account
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON_1 }}"
      - name: Building and pushing the image
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: us-central1-docker.pkg.dev
          project_id: development-262721
          image_name: draw-draw-ink/ddi-nui
          image_tag: ${{ github.sha }}
          dockerfile: ./Dockerfile
          context: .
